spring:
  application:
      name: study
  sql:
    init:
      mode: never
  datasource:
    url: jdbc:h2:tcp://localhost/~/springsecurity
    username: security
    password: security
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace